#!/usr/bin/env python3
"""
Interactive script to set up Twilio credentials in .env file
"""
import os
from pathlib import Path

def setup_twilio():
    print("\n" + "="*60)
    print("🌾 KisanAI - Twilio Setup Helper")
    print("="*60 + "\n")
    
    print("Please provide your Twilio credentials.")
    print("Get them from: https://console.twilio.com/\n")
    
    # Get credentials from user
    account_sid = input("Enter your Twilio Account SID: ").strip()
    if not account_sid:
        print("❌ Account SID is required!")
        return
    
    auth_token = input("Enter your Twilio Auth Token: ").strip()
    if not auth_token:
        print("❌ Auth Token is required!")
        return
    
    phone_number = input("Enter your Twilio Phone Number (with country code, e.g., +1234567890): ").strip()
    if not phone_number:
        print("❌ Phone Number is required!")
        return
    
    admin_phone = input("Enter admin phone number to receive SMS (with country code): ").strip()
    if not admin_phone:
        print("❌ Admin phone number is required!")
        return
    
    # Create .env content
    env_content = f"""# Environment Configuration
# Auto-generated by setup_twilio.py

# Twilio SMS Configuration
TWILIO_ACCOUNT_SID={account_sid}
TWILIO_AUTH_TOKEN={auth_token}
TWILIO_PHONE_NUMBER={phone_number}

# Admin Contact Information
ADMIN_PHONE_NUMBER={admin_phone}

# Database Configuration
DATABASE_URL=sqlite:///./kisanai.db

# Security
SECRET_KEY=kisanai-secret-key-change-in-production-2024

# Application Settings
APP_NAME=KisanAI
DEBUG=True
"""
    
    # Write to .env file
    env_path = Path(__file__).parent / ".env"
    with open(env_path, "w") as f:
        f.write(env_content)
    
    print("\n✅ .env file updated successfully!")
    print("\n📋 Your configuration:")
    print(f"   Account SID: {account_sid}")
    print(f"   Auth Token: {'*' * 20}")
    print(f"   From Number: {phone_number}")
    print(f"   To Number: {admin_phone}")
    
    print("\n🔄 Next steps:")
    print("   1. Restart your backend server (Ctrl+C, then restart)")
    print("   2. Run: python test_sms.py")
    print("   3. Check your phone for test SMS")

if __name__ == "__main__":
    setup_twilio()
